name: Build and Push generator image

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
    tags:
      - '*'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: make test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make build
